version: '3.7'

services:

  predict:
    build:
      context: ./services/predict
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./models:/etc/models
    environment:
      MODEL_DIR: /etc/models
      MODEL_FILE_NAME: latePaymentsModel.pkl
