name: loanApp
channels:
  - defaults
dependencies:
  - flask==1.1.1
  - numpy==1.15.4
  - pandas==0.24.1
  - python==3.7.2
  - python-dateutil==2.7.5
  - pytz==2018.9
  - requests==2.22.0
  - scikit-learn==0.20.2
  - scipy==1.2.1
  - six==1.12.0
